---
- name: Pre-requisite configuration and Docker Engine setup
  hosts: all
  remote_user: debian
  become: true

  roles:
    - common
    - docker

- name: Setup the discovery backend on consul node
  hosts: consul
  remote_user: debian
  become: true

  roles:
    - consul
