---
- name: Setup Docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo debian-jessie main' state=present filename='docker'

- name: Adding Docker key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Refreshing packages
  apt: update_cache=yes
