---
- name: Setup pre-requisite packages
  apt: name=apt-transport-https update_cache=yes

- name: Setup Docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo debian-jessie main' state=present filename='docker'

- name: Add Docker key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Setup pip package
  easy_install: name=pip state=latest

- name: Setup docker-py package
  pip: name=docker-py

- name: Set IP variables
  set_fact:
    consul_ip: "{{ hostvars[groups['consul'][0]]['ansible_eth0']['ipv4']['address'] }}"
